spring:

  application:
    name: koperasi

  datasource:
    url: jdbc:postgresql://localhost:5432/koperasi_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  jpa:

    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085

logging:
  level:

    org:
      hibernate:
        SQL: DEBUG

    root: INFO